# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
    ]
