# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('quiz', '0002_question_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='S',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sessions.Session')),
            ],
            options={
                'verbose_name_plural': 'sessions',
                'verbose_name': 'session',
                'abstract': False,
            },
            bases=('sessions.session',),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(default='буде помилка / error \nжодне з перелічених / none of the mentioned'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='Спробуйте і переконайтеся.'),
        ),
    ]
