# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20161207_0626'),
    ]

    operations = [

        migrations.DeleteModel(
            name='S',
        ),
    ]
